### ISSUE TITLE
unar 1.10.1?

### ISSUE THREAD

**Issue by uoziod** [krocon/node-unpack-all#1]
Any chance you could update unar to the latest version?

**Comment by TheTechsTech** [comment]
Will look into it, I thought I had it set to download latest version from
source.

**Comment by TheTechsTech** [comment]
If you are on Linux box, then it will install latest version compatible. On
Windows or Mac command line version is still 1.8.1 that works correctly.
Unless you can point me to location of that version, I will be unable to
update it.

**Comment by krocon** [comment]
node-unpack-all  is just a wrapper (222 lines of code) to your unar installation. What is the problem with the latest unar version? Have  the parameter names changed?

**Comment by uoziod** [comment]
I can't recall if I installed unar manually on my MacOS, but I pretty certain that its binary of 1.8.1 is now in node_modules/all-unpacker/bin. Manual replacement of it by the 1.10.1 version from their website does the trick (that is unpacking of RAR v5 archives), but I thought this is something should be working out of the box.

**Comment by krocon** [comment]
I think you are talking about:  https://www.npmjs.com/package/all-unpacker.  This is a fork of my krocon/node-unpack-all.  Perhaps technoexpress can help.

**Comment by uoziod** [comment]
Right, I got here from the page you linked to :)

**Comment by TheTechsTech** [comment]
If your are using my fork, then the binary is either automatically install
using Linux package manager or downloaded if Windows or Mac and placed in
bin folder. This is done at package install. There is no manual copying and
it's not in the project repo folder.

**Comment by uoziod** [comment]
Ok, ok. I just wanted to share my experience.
Btw, initial install has been done less than a month ago if that is somehow interesting.

P.S: Manual copying (updating to 1.10.1) has been done by me. But I'm pretty sure that this is totally unnecessary.

**Comment by uoziod** [comment]
Issue is applicable to Windows too:
![image](https://user-images.githubusercontent.com/169145/55625085-04503b80-57a8-11e9-9f6e-dfd7a516a978.png)

**Comment by uoziod** [comment]
Issue is also applicable to Windows:
![image](https://user-images.githubusercontent.com/169145/55625134-2cd83580-57a8-11e9-8b1a-b7f5500ea8b6.png)

**Comment by TheTechsTech** [comment]
There is no issue, it downloading the correct and only version availability
for it.

**Comment by uoziod** [comment]
For Windows maybe. Just tried out to get one for Mac from [here](https://theunarchiver.com/command-line). Getting this:
![image](https://user-images.githubusercontent.com/169145/55628548-4af66380-57b1-11e9-92e6-27c7bc21c322.png)

**Comment by TheTechsTech** [comment]
Ok, will look into it, the ones the repo is pulling from are not coming
from that download location.

**Comment by TheTechsTech** [comment]
Only Mac version is 1.10.1, Windows still 1.8.1. just downloaded both
versions.
